//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace FileSystem.Entity
{
    /// <summary>
    /// 实体类File。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Serializable]
    public partial class File:BaseEntity
    {
		/// <summary>
		/// 
		/// </summary>
		public int FileID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string FileName { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string FileExt { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int? FileSize { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public byte[] FileData { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public DateTime? FileCreateTime { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public int? FilePID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public byte[] FileOwner { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public byte[] FileRole { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public byte[] FileOther { get; set; }
	}
}